# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'app' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app
  
  # Menu
  pod 'SlideMenuControllerSwift'
  
  # Networking
  pod 'Alamofire', '~> 3.4'
  
  # KeyboardManager
  pod 'IQKeyboardManagerSwift'
  
  # SwiftyJSON
  pod 'SwiftyJSON'

  target 'appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
