# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'app' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app
  
  # Menu
  pod 'SlideMenuControllerSwift'
  
  # Networking
  pod 'Alamofire'
  
  # Indicator
  pod 'MBProgressHUD'
  
  # KeyboardManager
  pod 'IQKeyboardManagerSwift'
  
  # SwiftyJSON
  pod 'SwiftyJSON'
  
  # Colors
  pod 'FlatUIColors'
  
  # Notification
  pod 'BRYXBanner'
  
  # Image donwload
  pod 'MapleBacon'
  
  # GoogleMaps
  pod 'GoogleMaps'
  
  # Raiting starts
  pod 'Cosmos', '~> 1.2'
  
  # Random data generator
  pod 'Fakery'
  pod 'SwiftRandom'
  
  # Location
  pod 'SwiftLocation'
  
  # Gallery Viewer
  pod 'SKPhotoBrowser'
  
  # QRCode reader
  pod 'QRCodeReader.swift'
  
  # PickerView
  pod 'ActionSheetPicker-3.0'
  
  pod 'ReachabilitySwift'

  target 'appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
